src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TaskRepository::class)]
class Task
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $expired_at = null;

    #[ORM\Column(length: 500)]
    private ?string $executor = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getExpiredAt(): ?\DateTimeImmutable
    {
        return $this->expired_at;
    }

    public function setExpiredAt(\DateTimeImmutable $expired_at): static
    {
        $this->expired_at = $expired_at;

        return $this;
    }

    public function getExecutor(): ?string
    {
        return $this->executor;
    }

    public function setExecutor(string $executor): static
    {
        $this->executor = $executor;

        return $this;
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Task;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('expired_at')
            ->add('executor')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Task::class,
        ]);
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use App\Form\TaskType;
use App\Repository\TaskRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TaskController extends AbstractController
{
    #[Route('/', name: 'app_index')]
    public function index(TaskRepository $repository): Response
    {
        return $this->render('task/index.html.twig', [
            'controller_name' => 'TaskController',
            'tasks' => $repository->findAll(),
            'title' => 'Все проекты'
        ]);
    }

    #[Route('/new', name: 'app_task_new', methods: ['GET', 'POST'])]
    public function new(Request $request, TaskRepository $taskRepository): Response
    {
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);
        $task->setCreatedAt(new \DateTimeImmutable('now'));
        if ($form->isSubmitted() && $form->isValid()) {
            $taskRepository->save($task, true);

            return $this->redirectToRoute('app_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ttt/new.html.twig', [
            'task' => $task,
            'form' => $form,
            'title' => 'Создание новой задачи',
            'tasks' => null
        ]);
    }

    #[Route('/task/{id}', name: 'app_task_show', methods: ['GET'])]
    public function show(Task $task): Response
    {
        return $this->render('ttt/show.html.twig', [
            'task' => $task,
            'tasks' => null,
            'title' => $task->getName(),
        ]);
    }

    #[Route('/task/{id}/edit', name: 'app_task_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Task $task, TaskRepository $taskRepository): Response
    {
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $taskRepository->save($task, true);

            return $this->redirectToRoute('app_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ttt/edit.html.twig', [
            'task' => $task,
            'form' => $form,
            'tasks' => null,
            'title' => 'Обновление информации'
        ]);
    }

    #[Route('/task/{id}', name: 'app_task_delete', methods: ['POST'])]
    public function delete(Request $request, Task $task, TaskRepository $taskRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$task->getId(), $request->request->get('_token'))) {
            $taskRepository->remove($task, true);
        }

        return $this->redirectToRoute('app_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
    <div class="d-flex w-100" style="min-width: 100%; position: relative;">
        {% include 'base/sidebar.html.twig' %}
        <div class="px-0 mx-0" style="width: 100%!important;">
            {% include 'base/header.html.twig' %}
            {% block body %} {% endblock %}
        </div>
    </div>
    </body>
</html>

templates/base/header.html.twig
<header class="d-flex justify-content-lg-between align-items-center py-3 border-bottom border-light border-1 px-0">
    <h3 class="fw-bold mx-5 my-0 lh-lg">
        {{ title }}
    </h3>
    {% if tasks in not null %}
    <div class="d-flex mx-5">
        <select class="form-select">
            <option value="asc" selected>По возрастанию</option>
            <option value="desc">По убыванию</option>
        </select>

        <a class="mx-2 btn btn-dark">Применить</a>
    </div>
    {% endif %}
</header>

templates/base/sidebar.html.twig
<style>
    .nav-link:hover{
        background: var(--bs-gray-500);
    }
</style>
<div class="d-flex flex-column flex-shrink-0 p-3 border-end border-light border-1 text-dark bg-white" style="width: 280px; height: 100vh">
    <div class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
            <g clip-path="url(#clip0_1101_1352)">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M19.2 0H12.8V8.27451L6.94904 2.42355L2.42355 6.94902L8.27453 12.8H0V19.2H8.27451L2.42355 25.0509L6.94904 29.5765L12.8 23.7254V32H19.2V23.7254L25.051 29.5765L29.5765 25.051L23.7254 19.2H32V12.8H23.7254L29.5765 6.94902L25.051 2.42354L19.2 8.27451V0Z" fill="#0D1421"/>
            </g>
            <defs>
                <clipPath id="clip0_1101_1352">
                    <rect width="32" height="32" fill="white"/>
                </clipPath>
            </defs>
        </svg>
        <span class="fs-4 mx-3 fw-bold lh-lg">Вариант 12</span>
    </div>
    {% if tasks is not null %}
    <div class="my-3">
        <input class="form-control" placeholder="Поиск">
    </div>
    <div class="mb-2 fw-bolder">
        <a>Все проекты</a>
    </div>
    <ul class="nav nav-pills flex-column mb-auto mx-3 fw-bolder">
        {% for task in tasks %}
            <li>
                <a href="{{ path('app_task_show', {'id': task.id}) }}" class="nav-link text-dark" aria-current="page">
                    {{ task.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="bottom mt-auto fw-light text-muted" style="line-height: 8px; font-size: 16px">
        <a class="btn btn-dark my-3" href="{{ path('app_task_new') }}">Создать новую задачу</a>
        <p>© Вариант 12.</p>
        <p>Анна Рябинина,</p>
        <p>Группа ПМ-19-2</p>
    </div>
</div>

templates/task/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TaskController!{% endblock %}
{% block body %}
<div class="body mx-5 container">
    <div class="row row-cols-3 row-cols-md-3 row-cols-sm-3 g-2 m-0">
        {% for task in tasks %}
        <div class="col-sm">
            <div class="card rounded">
                <div class="colored-line rounded-pill mx-3 my-3" style="height: 8px; width: 64px; background: red"></div>
                <div class="card-body">
                    <div class="name">
                        <h6>{{ task.name }}</h6>
                        <div class="fw-light lh-lg d-flex" style="font-size: 14px;">
                            <p class="text-muted m-0" style="    white-space: nowrap; /* Запрещаем перенос строк */
                        overflow: hidden; /* Обрезаем все, что не помещается в область */
                        text-overflow: ellipsis; /* Добавляем многоточие */">{{ task.description }}</p>
                        </div>
                        <div class="fw-light lh-lg d-flex" style="font-size: 14px;">
                            <p class="text-muted m-0">Истекает: </p>
                            <p class="mx-1 fw-bold text-dark m-0">{{ task.expiredAt|date("d-m-Y h:m") }}</p>
                        </div>
                        <div class="lh-lg d-flex" style="font-size: 14px;">
                            <p class="fw-light text-muted m-0">Ответственный: </p>
                            <p class="mx-1 fw-bold text-dark m-0">{{ task.executor }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/ttt/_delete_form.html.twig
<form method="post" action="{{ path('app_task_delete', {'id': task.id}) }}" onsubmit="return confirm('Вы уверены что хотите удалить это задание?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn btn-dark">Удалить</button>
</form>

templates/ttt/_form.html.twig
{{ form_start(form) }}
    <div class="d-flex">
        <p>
            Имя:
        </p> {{ form_widget(form.name) }}
    </div>
    <div class="d-flex">
        <p>
            Описание:
        </p> {{ form_widget(form.description) }}
    </div>
    <div class="d-flex">
        <p>
            Дата окончания:
        </p> {{ form_widget(form.expired_at) }}
    </div>
    <div class="d-flex">
        <p>
            Исполнитель:
        </p> {{ form_widget(form.executor) }}
    </div>
    <button class="btn btn-dark">{{ button_label|default('Сохранить') }}</button>
{{ form_end(form) }}

templates/ttt/edit.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    {{ include('ttt/_form.html.twig', {'button_label': 'Обновить'}) }}

    <a href="{{ path('app_index') }}">Назад</a>

    {{ include('ttt/_delete_form.html.twig') }}
{% endblock %}

templates/ttt/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Task{% endblock %}

{% block body %}
    <div class="mx-3">
        {{ include('ttt/_form.html.twig') }}
        <a class="btn btn-dark" href="{{ path('app_index') }}">Назад</a>
    </div>
{% endblock %}

templates/ttt/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task{% endblock %}

{% block body %}
    <h1>Задание</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Название</th>
                <td>{{ task.name }}</td>
            </tr>
            <tr>
                <th>Описание</th>
                <td>{{ task.description }}</td>
            </tr>
            <tr>
                <th>Дата создания</th>
                <td>{{ task.createdAt ? task.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Дата окончания</th>
                <td>{{ task.expiredAt ? task.expiredAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Исполнитель</th>
                <td>{{ task.executor }}</td>
            </tr>
        </tbody>
    </table>

    <div class="my-2">
        <a class="btn btn-dark" href="{{ path('app_index') }}">Назад</a>

        <a class="btn btn-dark" href="{{ path('app_task_edit', {'id': task.id}) }}">Изменить</a>
    </div>

    {{ include('ttt/_delete_form.html.twig') }}
{% endblock %}